export const POST_QUESTION_SUCCESS = 'POST_QUESTION_SUCCESS';
export const POST_QUESTION_ERROR = 'POST_QUESTION_ERROR';
export const DISPLAY_USER_MESSAGE = 'DISPLAY_USER_MESSAGE';
export const DISPLAY_IMAGE = 'DISPLAY_IMAGE';
