export const TEAM_SELECTED = 'TEAM_SELECTED';
export const LOCATION_SELECTED = 'LOCATION_SELECTED';
export const TEAM_MEMBER_LIST = 'TEAM_MEMBER_LIST';
export const TEAM_LIST = 'TEAM_LIST';
export const LOCATION_LIST = 'LOCATION_LIST';
export const SEARCH_TEAM_LIST = 'SEARCH_TEAM_LIST';
export const SEARCH_TEAM_MEMBER_LIST = 'SEARCH_TEAM_MEMBER_LIST';
export const SEARCH_LOCATION_LIST = 'SEARCH_LOCATION_LIST';
